### ISSUE TITLE
s/pakage/package/ in README

### ISSUE THREAD

**Issue by phoe** [marcoheisig/simplified-types#1]
There is a stray `pakage` in README that wants to be turned into a `package`.

**Comment by marcoheisig** [comment]
Fixed - by dropping the package type :)

I realized that if I allow such arcane types as `package`, I should also allow types like `hash-table` or `random-state`.  Or I could just treat them all as `t`. Since the purpose of this library is to simplify things, I went for the latter.

Anyway, thanks for reporting!
